github: FabioLolix
#patreon: FabioLolix
ko_fi: fabiololix
liberapay: FabioLolix
custom: ["https://www.paypal.com/donate?hosted_button_id=NJT3H9QXE4TWU", "https://buymeacoffee.com/FabioLoli", "https://sponsus.org/u/fabiololix", "https://en.tipeee.com/fabiololix"]
